# Generated by Django 3.0.11 on 2020-12-13 13:19

import api.fields
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsync_id', models.CharField(blank=True, max_length=55)),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('phone', models.CharField(max_length=14)),
                ('full_address', models.CharField(blank=True, max_length=512)),
                ('name_of_university', models.CharField(max_length=256)),
                ('graduation_year', api.fields.IntegerRangeField(blank=True)),
                ('cgpa', api.fields.IntegerRangeField(blank=True)),
                ('experience_in_months', api.fields.IntegerRangeField()),
                ('current_work_place_name', models.CharField(max_length=256)),
                ('applying_in', models.CharField(choices=[('Mobile', 'Mobile'), ('Backend', 'Backend')], max_length=10)),
                ('expected_salary', api.fields.IntegerRangeField()),
                ('field_buzz_reference', models.CharField(blank=True, max_length=256)),
                ('github_project_url', models.URLField(max_length=512)),
                ('cv_file', jsonfield.fields.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
