# Generated by Django 3.0.11 on 2020-12-19 08:40

import api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='cgpa',
            field=api.fields.FloatRangeField(blank=True),
        ),
    ]
