# Generated by Django 3.0.11 on 2020-12-23 09:59

import api.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201219_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='cgpa',
            field=api.fields.FloatRangeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='current_work_place_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='info',
            name='experience_in_months',
            field=api.fields.IntegerRangeField(null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='graduation_year',
            field=api.fields.IntegerRangeField(),
        ),
    ]
