# Generated by Django 3.0.11 on 2020-12-23 10:03

import api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201223_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='experience_in_months',
            field=api.fields.IntegerRangeField(blank=True, null=True),
        ),
    ]
